
on:
  workflow_call:
    inputs:
      build-version:
        description: 'The version to build'
        required: true
        type: string
      profile-data-path-archive:
        description: 'The path to the zip archive containing the profile data'
        required: false
        type: string

jobs:
  windows-profile-build:
    # Edited from floorp build's windows profile build
    runs-on: windows-latest

    steps:

 

      - name: Generate 
        run: |
          $Env:USE_MINTTY = "0"

          mkdir mozilla-source
          cd mozilla-source
          curl -O https://hg.mozilla.org/mozilla-central/raw-file/default/python/mozboot/bin/bootstrap.py
          python3 bootstrap.py

          cd mozilla-unified
          python mach configure --enable-bootstrap
          $env:PATH=c:/mozilla-build/msys2/usr/bin:$PATH
          ./mach --no-interactive bootstrap --application-choice browser
          $env:LLVM_PROFDATA = $HOME + '/.mozbuild/clang/bin/llvm-profdata.exe'; $env:JARLOG_FILE = 'en-US.log'; python mach python build/pgo/profileserver.py --binary c:/artifact/zen/zen.exe
          
      - name: Publish merged.profdata
        uses: actions/upload-artifact@v4
        with:
          path: merged.profdata

      - name: Publish en-US.log
        uses: actions/upload-artifact@v4
        with:
          path: en-US.log

