
on:
  workflow_call:
    inputs:
      build-version:
        description: 'The version to build'
        required: true
        type: string
      profile-data-path-archive:
        description: 'The path to the zip archive containing the profile data'
        required: false
        type: string

jobs:
  windows-profile-build:
    # Edited from floorp build's windows profile build
    runs-on: windows-latest

    steps:


      - uses: actions/checkout@v4
        name: Clone 

      - name: Setup 
        run: |
          (New-Object System.Net.WebClient).DownloadFile("https://ftp.mozilla.org/pub/mozilla/libraries/win32/MozillaBuildSetup-Latest.exe","C:\MozillaBuildSetup-Latest.exe")
          C:\MozillaBuildSetup-Latest.exe /S | out-null

      - name: Install Node.js and pnpm
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm
          
      - name: Install dependencies
        run: |
          pnpm i

      - name: Download
        run: pnpm surfer download

      - name: Generate 
        run: |
          $Env:USE_MINTTY = "0"

          $workspace_dir = [regex]::replace($env:GITHUB_WORKSPACE, "^([A-Z]):", { "/" + $args.value.Substring(0, 1).toLower() }) -replace "\\","/"

          echo $workspace_dir
          cd $workspace_dir
          cd engine
          python --version
          python mach configure --enable-bootstrap
          $env:PATH=/c/mozilla-build/msys2/usr/bin:$PATH
          ./mach --no-interactive bootstrap --application-choice browser
          $env:LLVM_PROFDATA = $HOME + '/.mozbuild/clang/bin/llvm-profdata.exe'; $env:JARLOG_FILE = 'en-US.log'; python mach python build/pgo/profileserver.py --binary /c/artifact/zen/zen.exe
          
      - name: Publish merged.profdata
        uses: actions/upload-artifact@v4
        with:
          path: merged.profdata

      - name: Publish en-US.log
        uses: actions/upload-artifact@v4
        with:
          path: en-US.log

